urls.py
from django.conf.urls.defaults import *

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    (r'^$', 'money_views.views.index'),
    (r'^any_account$', 'money_views.views.any_account'),
    (r'^accounts/(?P<key>[0-9a-f+]+)$', 'money_views.views.account'),
    (r'^accounts/(?P<key>[0-9a-f+]+)/csv$', 'money_views.views.account_csv'),
    (r'^accounts/(?P<key>[0-9a-f+]+)/modify$', 'money_views.views.modify'),
    (r'^accounts/(?P<key>[0-9a-f+]+)/categorize$', 'money_views.views.batch_categorize'),
    (r'^accounts/(?P<key>[0-9a-f+]+)/categorize/apply$', 'money_views.views.apply_categorize'),

    (r'^accounts/(?P<key>[0-9a-f]+)/transactions/new$', 'money_views.views.new_transaction'),

    (r'^transaction/(?P<guid>[0-9a-f]+)/files$', 'money_views.views.transaction_files'),
    (r'^transaction/(?P<guid>[0-9a-f]+)/files/upload$', 'money_views.views.transaction_upload_file'),
    (r'^transaction/(?P<guid>[0-9a-f]+)/files/delete/(?P<hash>[0-9a-f]+)$', 'money_views.views.transaction_delete_file'),

    (r'^api/change_memo$', 'money_views.api.change_memo'),
    (r'^api/change_account$', 'money_views.api.change_account'),
    (r'^api/transactions$', 'money_views.api.get_transactions'),

    (r'^static/(?P<path>.*)$', 'django.contrib.staticfiles.views.serve'),

    # Uncomment the admin/doc line below to enable admin documentation:
    (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    (r'^admin/', include(admin.site.urls)),

    # Login
    (r'^accounts/login/$', 'django.contrib.auth.views.login', {'template_name': 'login.html'}),
)

gnucash_data/models.py
import errno
import hashlib
import io
import os
import psutil
import re
import shutil
import socket

from decimal import Decimal
from PIL     import Image

from django.core.files import uploadedfile
from django.db         import connections, models
from django.db.models  import Max

import settings


class Book(models.Model):
  from_gnucash_api = True

  guid = models.CharField(max_length=32, primary_key=True)
  root_account = models.ForeignKey('Account', db_column='root_account_guid')

  class Meta:
    db_table = 'books'

  def __unicode__(self):
    return 'Root account: %s' % self.root_account


class Account(models.Model):
  from_gnucash_api = True

  guid = models.CharField(max_length=32, primary_key=True)
  name = models.CharField(max_length=2048)
  parent_guid = models.CharField(max_length=32, null=True)
  type = models.CharField(max_length=2048, db_column='account_type')
  description = models.CharField(max_length=2048)
  placeholder = models.BooleanField()

  _balances = {}
  _root = None
  _all_accounts = None
  _order = None

  class Meta:
    db_table = 'accounts'

  def __unicode__(self):
    return self.path

  @staticmethod
  def from_path(path):
    parts = path.split(':')
    a = Account.get_root()
    if len(parts) > 0:
      for p in parts:
        found = False
        for c in a.children:
          if c.name == p:
            found = True
            a = c
            break
        if not found:
          raise ValueError("Invalid account path '%s'" % path)
    return a

  @staticmethod
  def get_root():
    Account._ensure_cached()
    return Account._root

  @staticmethod
  def get(guid):
    Account._ensure_cached()
    return Account._all_accounts[guid]['account']

  @staticmethod
  def get_all():
    Account._ensure_cached()
    return [obj['account'] \
      for obj in Account._all_accounts.itervalues()]

  @staticmethod
  def _ensure_cached():
    if Account._root is None:
      Account._root = Book.objects.get().root_account

    if Account._all_accounts is None:
      def _path(account):
        if account.parent_guid is None:
          return account.name
        parts = []
        a = account
        while not a.is_root:
          parts.append(a.name)
          a = Account.get(a.parent_guid)
        parts.reverse()
        return ':'.join(parts)

      Account._all_accounts = {}
      accounts = list(Account.objects.all())

      for a in accounts:
        Account._all_accounts[a.guid] = {
          'account': a,
          'path': '',
          'children': [],
        }
      for a in accounts:
        Account._all_accounts[a.guid]['path'] = _path(a)
        if a.parent_guid is not None:
          Account._all_accounts[a.parent_guid]['children'].append(a)
      for a in accounts:
        Account._all_accounts[a.guid]['children'] \
          .sort(key=lambda a: a.name.lower())

    if Account._order is None:
      def _build_order(account):
        Account._order.append(account.guid)
        for a in account.children:
          _build_order(a)
      Account._order = []
      _build_order(Account.get_root())

  @staticmethod
  def clear_caches():
    Account._balances = {}
    Account._root = None
    Account._all_accounts = None
    Account._order = None

  @property
  def description_or_name(self):
    if self.description:
      return self.description
    else:
      return self.name

  @property
  def balance(self):
    if self.guid not in Account._balances:
      #return sum(s.amount() for s in self.split_set.all()) # SLOW
      cursor = connections['gnucash'].cursor()
      cursor.execute('''
          SELECT value_denom, SUM(value_num)
          FROM splits
          WHERE account_guid = %s
          GROUP BY value_denom
        ''', [self.guid])
      amount = Decimal(0)
      for row in cursor.fetchall():
        amount += row[1] / row[0]
      Account._balances[self.guid] = amount
    return Account._balances[self.guid]

  @property
  def last_transaction_date(self):
    s = self.split_set.select_related(depth=1)
    utc = s.aggregate(max_date=Max('transaction__enter_date'))['max_date']
    return utc

  @property
  def has_updates(self):
    return (Update.objects.filter(account_guid=self.guid).count() > 0)

  @property
  def last_update(self):
    updates = Update.objects.filter(account_guid=self.guid)
    try:
      max_updated = updates.aggregate(max_updated=Max('updated'))['max_updated']
      return updates.filter(updated=max_updated).get()
    except:
      return None

  @property
  def children(self):
    Account._ensure_cached()
    return list(Account._all_accounts[self.guid]['children'])

  @property
  def is_root(self):
    return self.guid == Account.get_root().guid

  @property
  def path(self):
    Account._ensure_cached()
    return Account._all_accounts[self.guid]['path']

  @property
  def webapp_key(self):
    try:
      return unicode(settings.ACCOUNTS_LIST.index(self.path))
    except ValueError:
      return self.guid


class Update(models.Model):
  account_guid = models.CharField(max_length=32)
  updated = models.DateTimeField()
  balance = models.DecimalField(max_digits=30, decimal_places=5, null=True)

  class Meta:
    db_table = 'account_updates'

  def __unicode__(self):
    return "Account '%s' updated at %s (balance: %s)" % (
      Account.get(self.account_guid),
      self.updated,
      '?' if self.balance is None else '%0.2f' % self.balance)


class ImportedTransaction(models.Model):
  account_guid = models.CharField(max_length=32)
  tx_guid = models.CharField(max_length=32, null=True)
  source_tx_id = models.CharField(max_length=2048)
  update = models.ForeignKey(Update)

  class Meta:
    db_table = 'imported_transactions'

  def __unicode__(self):
    return "Account '%s', transaction '%s', source ID '%s'" % (
      Account.get(self.account_guid),
      Transaction.objects.get(guid=self.tx_guid),
      self.source_tx_id);


class Transaction(models.Model):
  from_gnucash_api = True

  guid = models.CharField(max_length=32, primary_key=True)
  post_date = models.DateField()
  enter_date = models.DateTimeField()
  description = models.CharField(max_length=2048)

  _cached_transactions = {}

  class Meta:
    db_table = 'transactions'

  def __unicode__(self):
    return '%s | %s' % (self.post_date, self.description)

  def attach_file(self, f):
    return File._new_with_transaction(f, self)

  @property
  def any_split_has_memo(self):
    for split in self.splits:
      if not split.memo_is_id_or_blank:
        return True
    return False

  @staticmethod
  def is_id_string(s):
    return bool(re.search('id:|ref:|t(x|rans(action)?) *id', s, re.I))

  @property
  def splits(self):
    if self.guid in Transaction._cached_transactions:
      return Transaction._cached_transactions[self.guid]['splits']
    else:
      return self.split_set.all()

  @staticmethod
  def cache_from_splits(splits):
    transactions = Transaction.objects \
      .filter(guid__in=(s.transaction.guid for s in splits))
    splits = Split.objects \
      .select_related(depth=2) \
      .filter(transaction__guid__in=(t.guid for t in transactions))
    for tx in transactions:
      Transaction._cached_transactions[tx.guid] = {
        'transaction': tx,
        'splits': [],
      }
    for s in splits:
      Transaction._cached_transactions[s.transaction.guid]['splits'].append(s)

  @staticmethod
  def clear_caches():
    Transaction._cached_transactions = {}


class Split(models.Model):
  from_gnucash_api = True

  guid = models.CharField(max_length=32, primary_key=True)
  account = models.ForeignKey(Account, db_column='account_guid')
  transaction = models.ForeignKey(Transaction, db_column='tx_guid')
  memo = models.CharField(max_length=2048)
  value_num = models.IntegerField()
  value_denom = models.IntegerField()

  class Meta:
    db_table = 'splits'

  def __unicode__(self):
    return '%s | %s | %0.2f' % (
      self.account,
      self.transaction,
      self.amount())

  @property
  def amount(self):
    return Decimal(self.value_num) / Decimal(self.value_denom)

  @property
  def is_credit(self):
    return self.amount > 0

  @property
  def memo_is_id_or_blank(self):
    return (not self.memo or Transaction.is_id_string(self.memo))

  @property
  def opposing_split_set(self):
    return [s for s in self.transaction.splits if s.account != self.account]

  @property
  def opposing_split(self):
    try:
      return self.opposing_split_set[0]
    except:
      return None

  @property
  def opposing_account(self):
    return self.opposing_split.account


class Lock(models.Model):
  from_gnucash_api = True

  hostname = models.CharField(max_length=255, db_column='Hostname')
  process_id = models.IntegerField(db_column='PID', primary_key=True)

  class Meta:
    db_table = 'gnclock'

  def __unicode__(self):
    try:
      name = psutil.Process(int(self.process_id)).name
    except:
      name = 'unknown process'
    return '%s:%i (%s)' % (self.hostname, self.process_id, name)

  @staticmethod
  def can_obtain():
    return (Lock.objects.count() == 0)

  @staticmethod
  def check_can_obtain():
    if not Lock.can_obtain():
      lock = Lock.objects.all()[0]
      raise IOError('Cannot lock gnucash DB tables - locked by %s' % lock)

  @staticmethod
  def obtain():
    Lock.check_can_obtain()
    # TODO: How to prevent a race condition here?
    lock = Lock()
    lock.hostname = Lock._fake_hostname()
    lock.process_id = os.getpid()
    lock.save()
    return lock

  @staticmethod
  def _fake_hostname():
    try:
      import psutil
      return '%s@%s' % (psutil.Process(os.getpid()).name, socket.gethostname())
    except ImportError:
      return socket.gethostname()

  @staticmethod
  def release():
    lock = Lock.objects \
      .filter(hostname=Lock._fake_hostname()) \
      .filter(process_id=os.getpid())
    n = lock.count()
    if n != 1:
      raise IOError('Expected 1 lock; found %i' % n)
    lock.delete()


class File(models.Model):

money_templates/templates/account_block.html
{% load template_extras %}
<div class="block{% if account.webapp_key == '0' and showing_index %} block-first{% endif %}">
  <table class="account-block">
    <tr>
      <th>Account{% if accounts|length > 1 %} {{ forloop.counter }}{% endif %}:</th>
      <td>
        {% if showing_index or accounts|length > 1 %}
          <a href="{% url money_views.views.account account.webapp_key %}">{{ account.description_or_name }}</a>
        {% else %}
          {{ account.description_or_name }}
        {% endif %}
      </td>
    </tr>
    <tr>
      <th>Type:</th>
      <td>{{ account.type.title }}</td>
    </tr>
    <tr>
      <th>Balance:</th>
      <td>
        <span class="account-balance-info">
          {{ account.balance|format_dollar_amount_neg }}
          {% if account.balance == account.last_update.balance %}
            <i class="balance-title balance-match icon-ok" title="Balance matches source account"></i>
          {% else %}
            {% if account.has_updates %}
              {% if account.last_update.balance == None %}
                <span class="balance-title balance-unknown" title="Balance unverified">?</span>
              {% else %}
                <i class="balance-title balance-mismatch icon-remove"
                  title="Balance does not match (source: {{ account.last_update.balance|format_dollar_amount }})"></i>
              {% endif %}
            {% endif %}
          {% endif %}
        </span>
      </td>
    </tr>
    {% if account.has_updates %}
      <tr>
        <th>As of:</th>
        <td>{{ account.last_update.updated|utc_to_local|format_date_time }}</td>
      </tr>
    {% endif %}
    <tr>
      <th>Changed:</th>
      <td>
        {% if account.last_transaction_date %}
          {{ account.last_transaction_date|utc_to_local|format_date_time }}
        {% else %}
          (no transactions)
        {% endif %}
      </td>
    </tr>
  </table>
</div>

money_templates/templates/hidden_filter_form.html
<form action="{% url money_views.views.account current_accounts_key %}" method="get">
  {{ hidden_filter_form.as_p }}
  <input type="submit" value="Return to transactions list" />
  <div class="note">
    <b>NOTE</b>: Clicking the button above will show all of the transactions
    that were just modified, but the list may also include some additional
    transactions that already met all of the criteria for the current filter.
  </div>
</form>

money_templates/templates/login.html
{# adapted from https://docs.djangoproject.com/en/1.2/topics/auth/#django.contrib.auth.views.login #}

{# {% extends "base.html" %} #}
{# {% load url from future %} #}

{# {% block content %} #}

{% if form.errors %}
<p>Your username and password didn't match. Please try again.</p>
{% endif %}

<form method="post" action=".">
{% csrf_token %}
<table>
<tr>
    <td>{{ form.username.label_tag }}</td>
    <td>{{ form.username }}</td>
</tr>
<tr>
    <td>{{ form.password.label_tag }}</td>
    <td>{{ form.password }}</td>
</tr>
</table>

<input type="submit" value="login" />
<input type="hidden" name="next" value="{{ next }}" />
</form>

{# {% endblock %} #}

money_templates/templates/modify_form.html
<form action="{% url money_views.views.modify current_accounts_key %}" method="post">
  <table id="modify-fields" class="form-table">
    {{ modify_form.as_table }}
  </table>
  {% csrf_token %}
  <div class="warning">
    <b>WARNING</b>: This will change <b>ALL</b> of the currently visible
    transactions on <b>ALL</b> pages!  (If an amount range is provided,
    only transactions within that range will be modified).
  </div>
  <input type="submit" value="Modify transactions" />
</form>

money_templates/templates/new_transaction_form.html
<form action="{% url money_views.views.new_transaction current_accounts_key %}" method="post">
  <table id="filters-fields" class="form-table">
    {% for field in new_transaction_form.visible_fields %}
      <tr class="field-{{ field.html_name }}">
        <th>{{ field.label_tag }}:&nbsp;</th>
        <td>
          {{ field.errors }}
          {{ field }}
        </td>
      </tr>
    {% endfor %}
  </table>
  {% for field in new_transaction_form.hidden_fields %}
    {{ field }}
  {% endfor %}
  {% csrf_token %}
  <input type="submit" value="Add transaction" />
  <a href="#" class="hidden" id="copy-from-transaction">copy from transaction</a>
</form>

money_templates/templates/page_account_details.html
{% extends "page_base.html" %}

{% load template_extras %}
{% load query_string %}

{% block title %}
  Account details - {% if accounts|length > 1 %}multiple accounts{% else %}{{ account.description_or_name }}{% endif %}
{% endblock %}

{% block scripts %}
  <script type="text/javascript">
    var filteringAny = {% if any_filters_applied %}true{% else %}false{% endif %};
    var queryParams = {{ query_params_js|safe }};
    var regexChars = {{ regex_chars_js|safe }};
    var accounts = {{ accounts_js|safe }};
    var currentAccountIds = {{ current_accounts_js|safe }};
    var currentAccountsKey = {{ current_accounts_key_js|safe }};
    var numTransactions = {{ num_transactions_js|safe }};
    var apiFunctionUrls = {{ api_functions_js|safe }};
  </script>
  <script type="text/javascript" src="{{ STATIC_URL }}page_account_details.js"></script>
  <script type="text/javascript" src="{{ STATIC_URL }}account_block.js"></script>

  <script type="text/javascript" src="{{ STATIC_URL }}vendor/moment.min.js"></script>
  <script type="text/javascript" src="{{ STATIC_URL }}vendor/d3/d3.min.js"></script>
  <script type="text/javascript" src="{{ STATIC_URL }}vendor/c3-0.4.10/c3.min.js"></script>
  <script type="text/javascript" src="{{ STATIC_URL }}txactions_chart.js"></script>

  <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}vendor/c3-0.4.10/c3.min.css">
{% endblock %}

{% block body %}
  {# To avoid duplication of lots of HTML, this element is copied to all transactions #}
  {# using JavaScript, then the original is removed from the page. #}
  <select class="change-account">
    {% for account in all_accounts %}
      <option value="{{ account.guid }}">{{ account.path }}</option>
    {% endfor %}
  </select>
  <div class="block block-first">
    <a href="{% url money_views.views.index %}">Back to index</a>
  </div>
  {% for account in accounts %}
    {% include "account_block.html" %}
  {% endfor %}
  {% if accounts|length > 1 %}
    <div class="block">
      <b>Total balance:</b>
      {{ total_balance|format_dollar_amount_neg }}
    </div>
  {% endif %}
  {% include "txactions_chart.html" %}
  {% include "txactions_page_block.html" %}
  <div class="block" id="forms">
    <div id="form-links">
      <a class="toggle-form" data-form="filters" id="toggle-filters" href="#">Filters</a>
      <a class="toggle-form" data-form="modify" href="#">Modify</a>
      <a class="toggle-form" data-form="other" href="#">Other</a>
    </div>
    <div class="clear" id="before-forms" />
    <div id="form-filters" class="form block block-first">
      {% include "filter_form.html" %}
    </div>
    <div id="form-modify" class="form block">
      {% include "modify_form.html" %}
    </div>
    <div id="form-other" class="form block">
      <ul class="links">
        <li>
          <a href="{% url money_views.views.batch_categorize current_accounts_key %}">
            Batch categorize transactions
          </a>
        </li>
        <li>
          <a href="{% url money_views.views.account_csv current_accounts_key %}{% query_string %}">
            Download data
          </a>
        </li>
      </ul>
    </div>
  </div>
  <div class="block">
    <table class="transactions">
      <tr>
        <th class="date">Date</th>
        <th class="opposing_account">Opposing account</th>
        <th class="amount">Amount</th>
      </tr>

      {% for split in page.object_list %}
        <tr data-tx="{{ split.transaction.guid }}">
          <td class="description" colspan="3" data-value="{{ split.transaction.description }}">
            {% if accounts|length > 1 %}
              <span class="account-index" title="{{ split.account.description_or_name }}">{{ split.account|index1_in:accounts }}</span>
            {% endif %}
            {{ split.transaction.description }}
            <a title="Search Google" target="_blank" class="transaction-control search no-ul no-events"
              href="http://www.google.com/search?q={{ split.transaction.description|urlencode }}">

              <i class="icon-search"></i>
            </a>
            <a title="Manage files" target="_blank" class="transaction-control manage-files no-ul no-events"
              href="{% url money_views.views.transaction_files split.transaction.guid %}">

              {{ split.transaction.file_set.count }}
              <i class="icon-file-alt"></i>
            </a>
            {% if not split.transaction.any_split_has_memo %}
              <i class="transaction-control add-memo icon-edit" title="Add memo"></i>
            {% endif %}
          </td>
        </tr>

        {% for memo_split in split.transaction.splits %}
          <tr{% if memo_split.memo_is_id_or_blank %} class="hidden"{% endif %}
            data-tx="{{ split.transaction.guid }}" data-account="{{ memo_split.account.guid }}"
            data-split="{{ memo_split.guid }}">

            <td class="memo" colspan="3" data-value="{{ memo_split.memo }}"
              title="Memo for account '{{ memo_split.account.path }}'">

              {{ memo_split.memo }}
            </td>
          </tr>
        {% endfor %}

        <tr data-tx="{{ split.transaction.guid }}"
          data-split="{{ split.guid }}" data-opposing-split="{{ split.opposing_split.guid }}">

          <td class="date" data-value="{{ split.transaction.post_date|format_date }}">
            {{ split.transaction.post_date|format_date }}
          </td>
          <td class="opposing-account">
            {% if not one_opposing_account_filter_applied %}
              <a class="transaction-control filter-opposing-account no-ul" title="Filter on this opposing account"
                href="{% query_string 'opposing_accounts=split.opposing_account.guid' '' %}">

                <i class="icon-filter"></i>
              </a>
            {% endif %}
            {% if split.opposing_account %}
              <a class="opposing-account-name" title="Go to account '{{ split.opposing_account.path }}'"
                href="{% url money_views.views.account split.opposing_account.webapp_key %}">

                {{ split.opposing_account.description_or_name }}</a>

              <i class="change-opposing-account icon-caret-down" data-value="{{ split.opposing_account.guid }}"
                title="Change opposing account"></i>
            {% else %}
              No opposing account
            {% endif %}
          </td>
          <td class="amount {% if split.is_credit %}credit{% else %}debit{% endif %}"
            data-value="{{ split.amount }}">

            {{ split.amount|format_decimal }}
          </td>
        </tr>
      {% endfor %}

    </table>
  </div>
  {% include "txactions_page_block.html" %}
  {% if can_add_transactions %}
    <div class="block">
      <p>
        <strong>Add new transaction</strong>
      </p>
      {% include "new_transaction_form.html" %}
    </div>
  {% endif %}
{% endblock %}

money_templates/templates/page_apply_categorize.html
{% extends "page_base.html" %}

{% block title %}Categorize multiple transactions{% endblock %}

{% block body %}
  <div class="block block-first">
    <div class="note">
      Modified <b>{{ modified_tx_count }}</b> transaction{% if modified_tx_count != 1 %}s{% endif %}
      and created <b>{{ rule_count }}</b> rule{% if rule_count != 1 %}s{% endif %}.
    </div>
  </div>
  <div class="block">
    <ul class="links">
      <li>
        <a href="{% url money_views.views.account current_accounts_key %}">
          Back to account
        </a>
      </li>
      <li>
        <a href="{% url money_views.views.batch_categorize current_accounts_key %}">
          Categorize more transactions
        </a>
      </li>
    </ul>
  </div>
{% endblock %}

money_templates/templates/page_base.html
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, user-scalable=no" />
    <title>{% block title %}Account balances{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}style.css">
    <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}font-awesome.css">
    <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}select2.css">
    <script type="text/javascript" src="{{ STATIC_URL }}jquery.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}jquery.cookie.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}jquery.shiftcheckbox.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}jquery.selectfocus.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}jquery.hiddendimensions.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}select2.js"></script>
    {% block scripts %}
    {% endblock %}
  </head>
  <body>
    {% block body %}
    {% endblock %}
  </body>
</html>

money_templates/templates/page_index.html
{% extends "page_base.html" %}

{% block title %}Account balances{% endblock %}

{% block scripts %}
  <script type="text/javascript" src="{{ STATIC_URL }}page_index.js"></script>
  <script type="text/javascript" src="{{ STATIC_URL }}account_block.js"></script>
{% endblock %}

{% block body %}
  {% for account in accounts %}
    {% include "account_block.html" %}
  {% endfor %}
  <div class="block">
    Other account:
    <form action="{% url money_views.views.any_account %}" method="get">
      <ul id="select-accounts">
        <li>
          <label for="accounts-all">
            <input type="checkbox" name="accounts" value="all" id="accounts-all" />
            (all)
          </label>
        </li>
        {% for account in all_accounts %}
          {% if not account.placeholder %}
            <li>
              <label for="account-{{ account.guid }}">
                <input type="checkbox" name="accounts" value="{{ account.webapp_key }}" id="account-{{ account.guid }}" />
                <a href="{% url money_views.views.account account.webapp_key %}">{{ account.path }}</a>
              </label>
            </li>
          {% endif %}
        {% endfor %}
      </ul>
      <input type="submit" value="Go" />
    </form>
  </div>
{% endblock %}

money_templates/templates/page_modify.html
{% extends "page_base.html" %}

{% block title %}Modify account{% endblock %}

{% block body %}
  {% if errors %}
    <div class="block block-first">
      <div class="warning">
        Error(s) occurred: <br />
        {{ errors }}
      </div>
    </div>
  {% endif %}
  <div class="block{% if not errors %} block-first{% endif %}">
    {% if modified_tx_count %}
      <div class="note">
        Modified <b>{{ modified_tx_count }}</b> transaction{% if modified_tx_count != 1 %}s{% endif %}
        in account <b>{{ account.path }}</b> - set opposing account to
        <b>{{ opposing_account.path }}</b>.
      </div>
    {% else %}
      <div class="warning">
        No transactions were modified.
      </div>
    {% endif %}
  </div>
  <div class="block">
    {% include "hidden_filter_form.html" %}
  </div>
{% endblock %}

money_templates/templates/page_txaction_files.html
{% extends "page_base.html" %}

{% load template_extras %}

{% block title %}
  Transaction attachments - {{ transaction }}
{% endblock %}

{% block scripts %}
  <script type="text/javascript" src="{{ STATIC_URL }}page_txaction_files.js"></script>
{% endblock %}

{% block body %}
  <div class="block block-first">
    {{ transaction.post_date|format_date }} <strong>{{ transaction.description }}</strong> for {{ transaction.splits.0.amount|format_decimal }}<br />
    This transaction has {{ transaction.file_set.count }}
    attachment{{ transaction.file_set.count|pluralize }}.
    <a class="close-window no-ul" href="#">
      <i class="icon-remove"></i>
    </a>
  </div>
  {% for file in transaction.file_set.all %}
    <div class="block">
      {% if file.extension == '.pdf' %}
        <a href="{{ STATIC_URL }}{{ file.web_path }}">{{ file.filename }}</a>
      {% else %}
        {{ file.filename }}
      {% endif %}
      |
      <a class="delete-attachment"
        href="{% url money_views.views.transaction_delete_file transaction.guid file.hash %}">delete</a>
      <br />
      {% if file.extension != '.pdf' %}
        <img class="auto-resize" src="{{ STATIC_URL }}{{ file.web_path }}" />
      {% endif %}
    </div>
  {% endfor %}
  <div class="block">
    <form method="post" enctype="multipart/form-data" action="{% url money_views.views.transaction_upload_file transaction.guid %}">
      Upload image or PDF:<br />
      {# http://stackoverflow.com/a/12673480/106302 #}
      <input type="file" name="file" accept="image/*,application/pdf" /><br />
      <input type="submit" value="Upload" />
      {% csrf_token %}
    </form>
  </div>
{% endblock %}